In [ ]:
# Indexing: It allows you to access and manipulate individuals elements, rows, columns, and even sub-arrays within array.

In [2]:
import numpy as np
array = np.arange(1, 10)
print(array)

[1 2 3 4 5 6 7 8 9]


In [5]:
array[2]

np.int64(3)

In [6]:
array_2d = np.random.randint(1,20,(2,3))
print(array_2d)

[[ 7 13  6]
 [13  9  3]]


In [11]:
array_2d[:,2]

array([6, 3], dtype=int32)

In [17]:
array_2d[1,2]

np.int32(3)

In [18]:
print(array)

[1 2 3 4 5 6 7 8 9]


In [19]:
array[-1]

np.int64(9)

In [20]:
array[-2]

np.int64(8)

In [21]:
array_2d

array([[ 7, 13,  6],
       [13,  9,  3]], dtype=int32)

In [28]:
array_2d[-2,-3]

np.int32(7)

In [ ]:
# slicing: It allows you to access a range of elements in an array.
# It has format : array[start : stop : step ]
# start : It is the index to start
# stop : It is the index to stop at (exclusive)--> not included in the array
# step : It is the interval between elements or gap between elements.

In [29]:
print(array)

[1 2 3 4 5 6 7 8 9]


In [30]:
array[1:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
array[5:]

array([6, 7, 8, 9])

In [33]:
array[1:5]

array([2, 3, 4, 5])

In [34]:
array[4:8]

array([5, 6, 7, 8])

In [36]:
array[::3]

array([1, 4, 7])

In [37]:
arr_value = np.arange(30).reshape(6,5)
print(arr_value)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [45]:
arr_value[4:,3:]

array([[23, 24],
       [28, 29]])

In [ ]:
# Assign value to Numpy arrays

In [46]:
arr_variable = np.array([1,2,3,4,5,6])
print(arr_variable)

[1 2 3 4 5 6]


In [47]:
arr_variable[1] = 4

In [48]:
arr_variable

array([1, 4, 3, 4, 5, 6])

In [49]:
arr_variable[5] = 10
print(arr_variable)

[ 1  4  3  4  5 10]


In [50]:
arr_variable[1:4] = 0
print(arr_variable)

[ 1  0  0  0  5 10]


In [51]:
arr_variable[1:4] = 12,13,14
print(arr_variable)

[ 1 12 13 14  5 10]


In [57]:
arr_var2d = np.arange(10,20).reshape(2,5)
print(arr_var2d)

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [60]:
arr_var2d[0,1] = 20

In [61]:

arr_var2d

array([[10, 20, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [63]:
arr_var2d[0] = 1,2,3,4,5
arr_var2d

array([[ 1,  2,  3,  4,  5],
       [15, 16, 17, 18, 19]])

In [64]:
arr_var2d[:,4] = 10, 20
arr_var2d

array([[ 1,  2,  3,  4, 10],
       [15, 16, 17, 18, 20]])

In [ ]:
# fancy indexing: It allows you to access multiple elements of an array using an array of indices.
# Instead of using simple integers or slices, you can specify arrays or list of indices to access elements.

In [65]:
fancy_array = np.array([10, 20, 30, 40, 50])
fancy_array

array([10, 20, 30, 40, 50])

In [68]:
fancy_array[[1,3,4]]

array([20, 40, 50])

In [75]:
arr_data = np.random.randint(1,10,(3,3))
print(arr_data)

[[7 8 1]
 [7 7 7]
 [4 5 5]]


In [77]:
arr_data[:,[0, 2]]

array([[7, 1],
       [7, 7],
       [4, 5]], dtype=int32)