In [ ]:
# np.reshape() : It allows you to change the shape (dimensions) of an array without altering its data.
# rule: The total no of elements in the original array must match the total no of elements in the new shape.

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [2]:
arr.ndim

1

In [3]:
arr.shape

(6,)

In [4]:
# (2,3)

arr2 = np.reshape(arr,(2,3))
print(arr2)


[[1 2 3]
 [4 5 6]]


In [6]:
arr_data = np.array([1,2,3,4,5,6,7,8])
print(arr_data)

[1 2 3 4 5 6 7 8]


In [7]:
arr_data.size

8

In [10]:
arr_data2 = np.reshape(arr_data,(4,2))
print(arr_data2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [11]:
arr_data3 = np.reshape(arr_data,(2,2,2))
print(arr_data3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
arr_data3.ndim

3

In [13]:
arr_data3.size

8

In [ ]:
# np.max() : It returns the maximum value from the array.

In [14]:
arr_value = np.random.randint(0, 20, 15)
print(arr_value)

[ 9  4  9  7  7  7 18  0  2  5 18 18  8 15  4]


In [15]:
np.max(arr_value)

np.int32(18)

In [16]:
arr_value.ndim

1

In [17]:
arr_value1 = np.random.randint(10, 20, (4,5))
print(arr_value1)

[[14 13 15 17 16]
 [17 16 18 16 15]
 [11 11 18 14 13]
 [19 12 15 17 14]]


In [18]:
arr_value1.ndim

2

In [20]:
np.max(arr_value1,axis=0)

array([19, 16, 18, 17, 16], dtype=int32)

In [21]:
np.max(arr_value1,axis=1)

array([17, 18, 18, 19], dtype=int32)

In [ ]:
# np.argmax(): Returns the index of the maximum value in the array.

In [24]:
print(arr_value)

[ 9  4  9  7  7  7 18  0  2  5 18 18  8 15  4]


In [25]:
arr_value.size

15

In [27]:
arr_value[1]

np.int32(4)

In [28]:
np.argmax(arr_value)

np.int64(6)

In [29]:
print(arr_value1)

[[14 13 15 17 16]
 [17 16 18 16 15]
 [11 11 18 14 13]
 [19 12 15 17 14]]


In [32]:
np.argmax(arr_value1, axis=1)

array([3, 2, 2, 0])

In [ ]:
# np.min(): Returns the minimum value of the array.

In [33]:
arr_value

array([ 9,  4,  9,  7,  7,  7, 18,  0,  2,  5, 18, 18,  8, 15,  4],
      dtype=int32)

In [34]:
np.min(arr_value)

np.int32(0)

In [35]:
arr_value1

array([[14, 13, 15, 17, 16],
       [17, 16, 18, 16, 15],
       [11, 11, 18, 14, 13],
       [19, 12, 15, 17, 14]], dtype=int32)

In [38]:
np.min(arr_value1, axis=1)

array([13, 15, 11, 12], dtype=int32)

In [ ]:
# np.argmin(): Returns the index of minimum value of the array.

In [39]:
print(arr_value)

[ 9  4  9  7  7  7 18  0  2  5 18 18  8 15  4]


In [40]:
np.argmin(arr_value)

np.int64(7)

In [41]:
arr_value1

array([[14, 13, 15, 17, 16],
       [17, 16, 18, 16, 15],
       [11, 11, 18, 14, 13],
       [19, 12, 15, 17, 14]], dtype=int32)

In [44]:
np.argmin(arr_value1, axis=1)

array([1, 4, 0, 1])

In [ ]:
# np.concatenate() : It is used to join two or more arrays along specified axis.
# It's helpful when you want to combine arrays into a single array without modifying the data.

In [48]:
array = np.arange(1,7)
array2 = np.arange(7,14)
print(array)
print(array2)

[1 2 3 4 5 6]
[ 7  8  9 10 11 12 13]


In [49]:
array3 = np.concatenate([array, array2])
print(array3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13]


In [52]:
array4 = np.random.randint(1, 10, (2, 4))
array5 = np.random.randint(10, 20, (2, 4))
print(array4)
print(array5)

[[2 9 2 3]
 [8 2 6 6]]
[[17 15 15 11]
 [14 12 17 15]]


In [53]:
array6 = np.concatenate([array4, array5])
print(array6)

[[ 2  9  2  3]
 [ 8  2  6  6]
 [17 15 15 11]
 [14 12 17 15]]


In [ ]:
# concatenate along axis
# axis = 0 --> Row wise
# axis = 1 --- Column wise

In [54]:
array_data = np.array([[1,2],[3,4]])
array_data2 = np.array([[5,6],[7,8]])
print(array_data)
print(array_data2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [55]:
result = np.concatenate((array_data, array_data2), axis=0 )
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [56]:
result = np.concatenate((array_data, array_data2), axis = 1)
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# np.split(): It is used to split an array into multiple sub-arrays.
# You can specify the number of sub-arrays or provide specific indices where the splits should occur.
# It is useful when you want to divide data into equal parts or based on the certain positions in the array.

In [57]:
data = np.arange(1,7)
print(data)

[1 2 3 4 5 6]


In [60]:
x,y,z = np.split(data, 3)

In [61]:
print(x)

[1 2]


In [62]:
print(y)

[3 4]


In [63]:
print(z)

[5 6]


In [64]:
np.split(data,[2,4])

[array([1, 2]), array([3, 4]), array([5, 6])]

In [66]:
data3 = np.array([[1,2],[3,4],[5,6],[7,8]])
print(data3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [67]:
np.split(data3, 2, axis=0 )

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [68]:
np.split(data3, 2, axis=1)

[array([[1],
        [3],
        [5],
        [7]]),
 array([[2],
        [4],
        [6],
        [8]])]

In [ ]:
# np.sort(): It sorts the elemenst of an array and returns a new array with the elements sorted in ascending order by default.
# It can handle sorting in multiple dimensions (1D, 2D, 3D, etc).

In [70]:
array1d = np.array([3,1,5,2,4])
np.sort(array1d)

array([1, 2, 3, 4, 5])

In [71]:
array2d = np.random.randint(1, 20, (2,2))
print(array2d)

[[ 9  2]
 [14 16]]


In [72]:
np.sort(array2d, axis=1)

array([[ 2,  9],
       [14, 16]], dtype=int32)

In [73]:
np.sort(array2d, axis=0)

array([[ 9,  2],
       [14, 16]], dtype=int32)