In [4]:
import numpy as np

In [5]:
np.__version__

'2.1.2'

In [6]:
# Numpy array : It is collection of data type or elements.
# Numpy arrays are the foundation of most numerical computing in Python
# Because they offer efficient ways to store and manipulate large datasets.

# --> np.array() : It is used to create an array object from any iterable such as list, or another array.


In [7]:
my_list = [1, 2, 3]

array = np.array(my_list) 

print(array)

[1 2 3]


In [8]:
type(array)

numpy.ndarray

In [9]:
array.dtype

dtype('int64')

In [10]:
array2 = np.array([23, 25.5, 34.5], dtype=int)
print(array2)

[23 25 34]


In [11]:
array2.dtype

dtype('int64')

In [12]:
names = ['James', "Bob", "Rock"]

array_names = np.array(names,dtype=str)
print(array_names)

['James' 'Bob' 'Rock']


In [13]:
array_names.dtype

dtype('<U5')

In [14]:
array_names.size

3

In [15]:
# Multi-dimensional arrays: You can create 1D, 2D or 3D arrays by passing nested lists.

list = [1,2,3,4]
list2 = [5, 6, 7, 8]

array2d = np.array([[1,2,3,4], [5,6,7,8]])
print(array2d)


[[1 2 3 4]
 [5 6 7 8]]


In [16]:
array2d.ndim

2

In [17]:
array2d.shape

(2, 4)

In [18]:
array3d = np.array([[[1,2,3,4], [5,6,7,8]], [[1,2,3,4], [5,6,7,8]]])
print(array3d)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


In [19]:
array3d.ndim

3

In [20]:
array3d.shape

(2, 2, 4)

In [21]:
# np.zeros() : This function creates a array filled with elements as zeros.
# It is useful when you need an empty placeholder array with specific dimensions,
# for example intializing weights for machine learning models, prepering matrices for computation.

In [22]:
zeros_array = np.zeros(5)
print(zeros_array)

[0. 0. 0. 0. 0.]


In [23]:
zeros_array.size

5

In [24]:
zeros_array.shape

(5,)

In [25]:
zeros_array.ndim

1

In [26]:
zeros_2darray = np.zeros((3,5))
print(zeros_2darray)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
zeros_2darray.shape

(3, 5)

In [28]:
zeros_2darray.ndim

2

In [29]:
zeros_2darray.size

15

In [30]:
zeros_3darray = np.zeros((3,2,4))
print(zeros_3darray)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [31]:
zeros_3darray.ndim

3

In [32]:
zeros_3darray.size

24

In [33]:
zeros_3darray.shape

(3, 2, 4)

In [34]:
zeros_2darray[0] = [1,2,3,4,5]
print(zeros_2darray)

[[1. 2. 3. 4. 5.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [35]:
zeros_2darray.dtype

dtype('float64')

In [36]:
array = np.zeros(4, dtype=int)

In [37]:
print(array)

[0 0 0 0]


In [38]:
# np.ones() : This function creates a array filled with elements as ones (1). Simirlar to np.zeros()
# it can be used to intialize arrays of different shapes and data types.
# This function is useful when you need an array of specific shape with a default value of one, often as placeholder.

In [39]:
array_1d = np.ones(4, dtype=int)
print(array_1d)

[1 1 1 1]


In [40]:
array_1d.ndim

1

In [41]:
array_1d.size

4

In [42]:
array_1d.shape

(4,)

In [43]:
array_1d.dtype

dtype('int64')

In [44]:
array_2d = np.ones((3,4), dtype=int)
print(array_2d)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [45]:
array_2d.ndim

2

In [46]:
array_2d.size

12

In [47]:
array_2d.shape

(3, 4)

In [48]:
array_2d.dtype

dtype('int64')

In [49]:
array_3d = np.ones((4,3,5), dtype=int)
print(array_3d)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [50]:
array_3d.ndim

3

In [51]:
array_3d.size

60

In [52]:
array_3d.dtype

dtype('int64')

In [53]:
# np.eye() : It creates a 2d array (matrix) with ones on the main diagonal and zeros everywher else.
# This matrix is called identity matrix. Identity matrices are widely used in linear algebra.

In [54]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
matrix_eye = np.eye(4,4, k=-2, dtype=int)
print(matrix_eye)

[[0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]]


In [56]:
matrix_eye.size

16

In [57]:
matrix_eye.ndim

2

In [58]:
matrix_eye.shape

(4, 4)

In [59]:
matrix_eye.dtype

dtype('int64')

In [60]:
# np.full() : This function creates an array filled with specified value, which can be any number you choose.
# This function is similar to np.zeros() and np.ones(), 
# but it gives you more control by allowing you to define any initial vlaue for each elment in the array.

In [61]:
full_array = np.full(4, 8)
print(full_array)

[8 8 8 8]


In [62]:
full_2darray = np.full((3,4), 2, dtype=float)
print(full_2darray)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [63]:
full_2darray.ndim

2

In [64]:
full_2darray.size

12

In [65]:
full_2darray.dtype

dtype('float64')

In [66]:
full_3darray = np.full((4, 2,3), 9, dtype=float)
print(full_3darray)

[[[9. 9. 9.]
  [9. 9. 9.]]

 [[9. 9. 9.]
  [9. 9. 9.]]

 [[9. 9. 9.]
  [9. 9. 9.]]

 [[9. 9. 9.]
  [9. 9. 9.]]]


In [67]:
full_3darray.ndim

3

In [68]:
full_3darray.size

24

In [69]:
full_3darray.dtype

dtype('float64')

In [70]:
# np.arange() : This function creates an array with evenly spaced values within a given interval.
# It is similar to Python's built-in range() function, but returns an array instead of a list,
# and allows floating point values as well as integers.
# np.arange() is often used for generating squences of numbers, 
# which can be particularly useful for indexing, creating time intervals, or generating test data.

# np.arange(start, stop, step, dtype) --> where stop is exclusive or not included in the array.

In [71]:
arr = np.arange(5)
print(arr)

[0 1 2 3 4]


In [72]:
arr1 = np.arange(5, 10)
print(arr1)

[5 6 7 8 9]


In [73]:
arr3 = np.arange(0, 10, 4)
print(arr3)

[0 4 8]


In [74]:
arr4 = np.arange(0, 1, 0.2)
print(arr4)

[0.  0.2 0.4 0.6 0.8]


In [75]:
arr5 = np.arange(2, 20, 3, dtype = float)
print(arr5)

[ 2.  5.  8. 11. 14. 17.]


In [76]:
arr5.size

6

In [77]:
arr5.ndim

1

In [78]:
arr5.shape

(6,)

In [79]:
arr5.dtype

dtype('float64')

In [ ]:
# np.linspace() : This function generates an array of evenly spaced numbers over a specified intervalue.
# np.linspace() uses a specific step size to generates a defined number of points between a start and stop value.
# which is useful when you want a fixed number of samples between two values, especial for continous data.

In [82]:
arr1 = np.linspace(0, 10, num = 5, retstep = True)
print(arr1)

(array([ 0. ,  2.5,  5. ,  7.5, 10. ]), np.float64(2.5))


In [86]:
arr2 = np.linspace(5, 20, num = 10)
print(arr2)

[ 5.          6.66666667  8.33333333 10.         11.66666667 13.33333333
 15.         16.66666667 18.33333333 20.        ]


In [87]:
arr2.size

10

In [88]:
arr2.shape

(10,)

In [89]:
arr2.ndim

1

In [90]:
arr3 = np.linspace(0, 15, num= 10, dtype=int)
print(arr3)

[ 0  1  3  5  6  8 10 11 13 15]


In [ ]:
# np.random module: This module provides various functions to generate random numbers, arrays, and samples from different distribution.
# This is essential in data science, machine learning, and any applications that require randomness sampling.

In [95]:
rand_arr = np.random.rand(2,3)
print(rand_arr)

[[0.0312345  0.30416259 0.48468407]
 [0.9803046  0.58255991 0.86055469]]


In [96]:
rand_arr.ndim

2

In [99]:
randn_arr = np.random.randn(3,4)

In [100]:
print(randn_arr)

[[ 0.70179542  0.29919615 -0.23429504 -0.14843474]
 [ 0.44015855  1.77294339  0.17643682 -0.13894433]
 [ 0.81399505  0.57654775 -0.47721034  1.90357109]]


In [101]:
randn_arr.ndim

2

In [104]:
randint_arr = np.random.randint(0, 10, size = (2,2,2))
print(randint_arr)

[[[1 1]
  [6 7]]

 [[0 7]
  [3 5]]]


In [105]:
randint_arr.ndim

3