In [ ]:
# Operation with comparison operators
# Arithmetic Operations
# Statistical Operations

In [ ]:
# In Numpy, comprison operators (>,<,==,!=,>=,<=) can be applied directly to arrays to perform element-wise comparisons.
# These comparisons return Boolean arrays, where each element is either True or False based on the result of the comparison.
# This is useful for filtering, counting, or setting specific elements in the array based on certain conditions.

In [1]:
import numpy as np

In [2]:
array = np.array([10, 20, 30, 40, 50])
array

array([10, 20, 30, 40, 50])

In [4]:
# > 

result = array > 25
print(result)

[False False  True  True  True]


In [5]:
# <

result2 = array < 30
print(result2)

[ True  True False False False]


In [6]:
#  ==

result3 = array == 20
print(result3)

[False  True False False False]


In [7]:
# filtering

filtered_elements = array[array > 25]
print(filtered_elements)

[30 40 50]


In [ ]:
# NumPy allows you to combine multiple conditions using bitwise operators:
# & for "and"
# | for "or"
# ~ for "not"

In [9]:
filter_elements = array[(array == 10) | (array > 40)]
print(filter_elements)

[10 50]


In [ ]:
# Arithmetic Operations: In Numpy, arithmetic operations can be performed directly on arrays.
# These operations work between arrays or between an array and a scalar (single value).
# Basic arithmetic operators and functions in Numpy include:
# Addition (+) | np.add()
# Subtraction (-) | np.subtract()
# Multiplication (*) | np.multiply()
# Division (/) | np.divide()
# Exponentiation (**) | np.power()
# Modulus (%) | np.mod()

In [10]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

In [11]:
arr1 + arr2

array([11, 22, 33, 44, 55])

In [12]:
np.add(arr1,arr2)

array([11, 22, 33, 44, 55])

In [13]:
arr2-arr1

array([ 9, 18, 27, 36, 45])

In [14]:
np.subtract(arr2,arr1)

array([ 9, 18, 27, 36, 45])

In [15]:
arr1 * arr2

array([ 10,  40,  90, 160, 250])

In [16]:
np.multiply(arr1,arr2)

array([ 10,  40,  90, 160, 250])

In [17]:
arr2 / arr1

array([10., 10., 10., 10., 10.])

In [18]:
np.divide(arr2,arr1)

array([10., 10., 10., 10., 10.])

In [19]:
arr1 ** 2

array([ 1,  4,  9, 16, 25])

In [20]:
np.power(arr1,2)

array([ 1,  4,  9, 16, 25])

In [21]:
arr2 % arr1

array([0, 0, 0, 0, 0])

In [23]:
np.mod(arr2,arr1)

array([0, 0, 0, 0, 0])

In [24]:
arr1

array([1, 2, 3, 4, 5])

In [25]:
arr1 + 1

array([2, 3, 4, 5, 6])

In [ ]:
# Statistical Operations : It has various functions to perform statistical operation.

In [26]:
arr1

array([1, 2, 3, 4, 5])

In [27]:
np.sum(arr1)

np.int64(15)

In [29]:
np.prod(arr1)

np.int64(120)

In [30]:
np.mean(arr1)

np.float64(3.0)

In [31]:
np.std(arr1)

np.float64(1.4142135623730951)

In [32]:
np.var(arr1)

np.float64(2.0)

In [33]:
np.min(arr1)

np.int64(1)

In [34]:
np.max(arr1)

np.int64(5)

In [35]:
np.log(arr1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])